from django.conf.urls import patterns, url,include
from tpo import views

urlpatterns = patterns('',
        url(r'^$', views.home, name='home'),
        url(r'^main/$', views.main, name='main'),
        #url(r'^main/student/(?P<email>[\w\.]+@[a-zA-Z_]+?\.[a-zA-Z\.]{2,})$', views.student, name='student'),
        #url(r'^main/admin/(?P<email>[\w\.]+@[a-zA-Z_]+?\.[a-zA-Z\.]{2,})$', views.admin, name='admin'),
        url(r'^main/admin/$', views.admin, name='admin'),
        url(r'^main/admin/tprregister$', views.admintpr, name='admintpr'),
        url(r'^main/admin/adminregister$', views.adminregister, name='adminregister'),
        url(r'^main/student/$', views.student, name='student'),
        url(r'^main/register/$', views.register, name='register'),
        url(r'^main/post/$', views.post, name='post'),
        url(r'^main/tpr/$', views.tpr, name='tpr'),
        url(r'^main/student/willing/$', views.studwill, name='studwill'),
        url(r'^main/student/willing/(?P<comp_id>[0-9]+)/$', views.studwillcomp, name='studwillcomp'),
        url(r'^main/student/update/$', views.studentupdate, name='studupdate'),
        url(r'^main/student/grade/$', views.studentgrade, name='studgrade'),
        url(r'^main/student/resume/$', views.resume_upload, name='studresume'),
        url(r'^main/student/picture/$', views.picture_upload, name='studpic'),
        url(r'^main/admin/help/$', views.adminhelp, name='ad_help'),
        url(r'^main/admin/post/$', views.adminpost, name='ad_post'),
        url(r'^main/admin/company/$', views.admincompany, name='ad_company'),
        url(r'^main/admin/comp_will/$', views.admincompwill, name='ad_compwill'),
        #url(r'^main/admin/help/(?P<admin_id>[0-9]+)/$', views.adminhelp, name='ad_help'),
        #url(r'^main/admin/post/(?P<admin_id>[0-9]+)/$', views.adminpost, name='ad_post'),
        #url(r'^main/admin/company/(?P<admin_id>[0-9]+)/$', views.admincompany, name='ad_company'),
        url('', include('social.apps.django_app.urls', namespace='social')),
    	url('', include('django.contrib.auth.urls', namespace='auth')),
        )